added pre-commit

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,6 +13,34 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
+      - name: Fetch all branches and tags
+        run: git fetch --prune --unshallow
+
+      - name: Determine Branch and Commit Count
+        id: determine_branch_and_commit_count
+        run: |
+          BRANCH=$(echo "${{ github.ref }}" | awk -F'/' '{print $NF}')
+          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
+          MAJOR_VERSION=$(echo $CURRENT_VERSION | cut -d'.' -f1)
+          MINOR_VERSION=$(echo $CURRENT_VERSION | cut -d'.' -f2)
+          PATCH_VERSION=$(echo $CURRENT_VERSION | cut -d'.' -f3)
+          if [ "$BRANCH" = "master" ]; then
+            NEW_VERSION=$(($MAJOR_VERSION + 1)).0.0
+          elif [[ "$BRANCH" == "feature"* ]]; then
+            NEW_VERSION=$MAJOR_VERSION.$(($MINOR_VERSION + 1)).0
+          elif [[ "$BRANCH" == "fixes"* ]]; then
+            NEW_VERSION=$MAJOR_VERSION.$MINOR_VERSION.$(($PATCH_VERSION + 1))
+          else
+            echo "::error::Unsupported branch"
+            exit 1
+          fi
+          mvn versions:set -DnewVersion=$NEW_VERSION -DgenerateBackupPoms=false
+          git config --global user.email "action@github.com"
+          git config --global user.name "GitHub Action"
+          git commit -am "Bump version to $NEW_VERSION"
+          git push origin master
+          echo "::set-output name=version::$NEW_VERSION"
+
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
